### ISSUE TITLE
PeLib is missing the 'BUSY' file

### ISSUE THREAD

**Issue by tenko** [rochus-keller/LeanQt#1]
I believe the repo 'https://github.com/rochus-keller/PeLib/' is missing the 'BUSY' file.

It failed for me when I tried the build procedure.

The repo seems to be not be updated for some time and is probably just missing
a GIT commit you have locally.

**Comment by rochus-keller** [comment]
Oops, I forgot to push to Github, sorry; too many repositories involved as it seems ;-)
It's now up and corresponds to the tested configuration.
