### ISSUE TITLE
qt as a set of libraries

### ISSUE THREAD

**Issue by ghost** [rochus-keller/LeanQt#10]
hi it's not an issue, I'm only to talk. About the philosophy of providing qt as a set of libraries not a framework, did you know about copperspice when you started this effort? copperspice is exactly that: qt as a set of libraries.

**Comment by rochus-keller** [comment]
Thanks for the hint. I'm well aware of Copperspice and had a close look at it some years ago. Copperspice might be a very useful library, especially for people who prefer template meta programing, but it is not Qt. Even if it originally has been derived from Qt 4, I cannot use it as a drop-in replacement for Qt. 

LeanQt on the other hand is just original Qt refactored and decluttered to an essential feature set and an easily integratable/bootstrappable build, but compatible with the original API. It is supposed to be compatible with all my existing Qt applications, so I can choose whether I want to build with original Qt or LeanQt without modifications or ifdefs.
