### ISSUE TITLE
How to build from source on MSYS2 UCRT64?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/LeanQt#12]

**Comment by rochus-keller** [comment]
Have you tried? What happens?

**Comment by ghost** [comment]
> Have you tried? What happens?

Not yet. I only care about LeanQt itself. I don't want to build Oberon+ command line compiler or Oberon+ IDE. I also wanted to know if I could use MSYS2 UCRT64's lua package (`mingw-w64-ucrt-x86_64-lua`) instead of having to build my own.

**Comment by rochus-keller** [comment]
LeanQt is usually not used stand-alone, but as part of a project (e.g. Oberon+ IDE or LeanCreator). I successfully built LeanCreator (together with LeanQt) using https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev2/i686-12.2.0-release-win32-dwarf-msvcrt-rt_v10-rev2.7z. I didn't use MSYS2 UCRT64, but I don't see a reason why it shouldn't work.

**Comment by ghost** [comment]
> LeanQt is usually not used stand-alone, but as part of a project (e.g. Oberon+ IDE or LeanCreator). I successfully built LeanCreator (together with LeanQt) using https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev2/i686-12.2.0-release-win32-dwarf-msvcrt-rt_v10-rev2.7z. I didn't use MSYS2 UCRT64, but I don't see a reason why it shouldn't work.

OK. I got it.
