### ISSUE TITLE
How to port Qt5 applications to LeanQt?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/LeanQt#13]
For example, this Qt5 application: https://github.com/royqh1979/RedPanda-CPP

**Comment by rochus-keller** [comment]
There are different ways.

I usually write a BUSY file with all required implementation files; it's up to you whether you want to have all stuff in a single or in multiple BUSY files; it's also necessary to explicitly add Moc and Rcc declarations with the affected files (.qrc for the Rcc declaration; .h and .cpp where Q_OBJECT macros are used for the Moc declaration). There are several examples in my repositories how to do that (e.g. Oberon, or CrossLine, or LisaPascal).

Alternatively you can also continue to use Qmake and Qt Creator, but then you have to build a LeanQt version static or shared library and properly reference it from the Qmake .pro file (and don't forget to disable Qt like `QT -= core gui`).

**Comment by rochus-keller** [comment]
I quickly had a look at the RedPandaIDE .pro files. It requires printsupport and svg, both of which are not supported by LeanQt; I plan to implement print support in future, and QSvg is likely to build on top of LeanQt, but it's not out-of-the-box. From my experience with Qt Creator -> LeanCreator migration I think it's feasible to add #ifdefs to deactivate the code depending on the features not available yet, but expect some effort.

**Comment by rochus-keller** [comment]
can we close this?
