### ISSUE TITLE
Is LeanQt being actively maintained?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/LeanQt#14]
By being actively maintained I mean bug fixes and security fixes (could be taken from upstream Qt). Btw, I want to ask you what is the license of LeanQt. You said you forked from Qt 5.6.3 which is the last version licensed under both LGPLv2.1 and LGPLv3. So the license of LeanQt is LGPLv2.1 or LGPLv3? Because LGPLv2.1 and LGPLv3 are incompatible, if you want to take patches from upstream Qt you have to switch to LGPLv3-only. This is at least what I think. You might have better knowledge about open source licensing than me, so please correct me if I was wrong.

**Comment by rochus-keller** [comment]
> By being actively maintained I mean bug fixes and security fixes

I make changes according to my own observations and demand and continue to do so for the years to come, but I'm not following Qt fixes; but it's an open source project, so anyone can contribute.

> So the license of LeanQt is LGPLv2.1 or LGPLv3? 

Right. 

> if you want to take patches from upstream Qt you have to switch to LGPLv3-only

A patch is barely protected by copyright, and the latest when you have to make adjustments to it for LeanQt compatibility I don't see an issue.

**Comment by rochus-keller** [comment]
can we close this?
