### ISSUE TITLE
Provide Python wheel / binding

### ISSUE THREAD

**Issue by brenthuisman** [rochus-keller/LeanQt#15]
Qt provide a Python binding through PySide. These are very fat wheels though (100MB+). LeanQT could have its own binding with a much lighter wheel. Is this on the radar and are you interested in providing this?

**Comment by rochus-keller** [comment]
Personally I rarely use Python and don't need a binding. But since the API is the same as for Qt I assume that it should be possible to build PySide with LeanQt with little modifications.
