### ISSUE TITLE
Will there be LeanQt6?

### ISSUE THREAD

**Issue by superchick** [rochus-keller/LeanQt#17]
This fork is adapted to work on Windows 7, too:

https://github.com/crystalidea/qt6windows7

**Comment by rochus-keller** [comment]
> Will there be LeanQt6? 

No, definitely not.

> This fork is adapted to work on Windows 7, too:

Then I recommend you use that one.

**Comment by superchick** [comment]
> > This fork is adapted to work on Windows 7, too:
> 
> Then I recommend you use that one.

No, thanks. I'm using Windows 10.

**Comment by rochus-keller** [comment]
Even better, then just use original Qt6 if you need it.
