### ISSUE TITLE
Could you shift build system to CMake?

### ISSUE THREAD

**Issue by setoutsoft** [rochus-keller/LeanQt#19]
I believe BUSY is enough for you. However, CMake can make it more common.

**Comment by rochus-keller** [comment]
Well, you're the first who asks for this in two years. I initially planned to implement a cmake generator (as there is already a qmake generator), but there were more important priorities, and nobody seemed to miss it. You can e.g. build a shared library version of LeanQt with BUSY and just use this pre-built version in your project. That said, BUSY is indeed good enough for me so far, and I use it in all of my projects, the largest ones > 1 million SLOC.

**Comment by setoutsoft** [comment]
Thank you! I'm trying to use vscode to debug leanQt to understand how it work. Without cmake, I had to build it using BUSY, and run examples. After that, I use vscode to attach to that running example, which made it very inconvenient.

**Comment by rochus-keller** [comment]
You could use https://github.com/rochus-keller/leancreator/ instead of vscode, or generate a qmake project and use qt creator. I myself use mostly LeanCreator for all projects.

**Comment by setoutsoft** [comment]
thank you!
