### ISSUE TITLE
Network support would be great 

### ISSUE THREAD

**Issue by MangoCats** [rochus-keller/LeanQt#2]
Great idea for QtLite, I was surprised yesterday that the default desktop install for Qt has bloated to 8.6GB in Windows!

I used to do a lot of QWidgets applications, but recently I am leaning more towards http server interfaces over Qt Core, with http://stefanfrings.de/qtwebapp/tutorial/index.html which has been around a lot longer than the official Qt server...

I understand the license concern, but a number of significant improvements have been made in Qt Core through 5.12... not sure how much value is in 13 to 15, but I definitely use stuff from 12 a lot.

**Comment by rochus-keller** [comment]
Thanks. Can you specify, what features from Qt 5.12 you need which were not available in Qt 5.6?

Migrating QtNetwork to LeanQt will probably take 2 to 4 calendar weeks from now.

**Comment by MangoCats** [comment]
QRandomGenerator comes to mind first, I used to import my own Mersenne
Twister implementation before that came in 5.10

OAuth support from 5.8 is great when you need it.

Ssl upgrades in 5.10 are pretty much essential for some secure TCP
connection work anymore.

I haven't used Qt remote objects from 5.12, only because I have been
rolling my own solutions for that since 2010, but if I were to start a new
big project they would definitely be evaluated as a potential solution...

There are some QtNetwork improvements around SSL sockets in Windows in 5.13
& 14 that might be missed if you don't have them...

I'm not such a Bluetooth fan, but they also did a lot of Bluetooth support
development during those versions up to 5.14, which if they were sensible
is optional to include.

Of course 5.15 starts the aggressive depreciation warnings for Qt6
transition, but it also modernizes QtNetwork for TLS 1.3.....

**Comment by rochus-keller** [comment]
Thanks. That's a lot of stuff. Not sure yet whether I should support OpenSSL; I did my own implementations of TCP and Bluetooth connections based on Mbed TLS. Concerning the classes missing from Qt 5.6 maybe you can try whether they would compile with the resulting leanqt; I wouldn't want to integrate them because they are not available under LGPL v2.1; but a separate package which people could use with an explicitly different license would be ok.

**Comment by MangoCats** [comment]
I am curious if anything specific in LGPL 3 is of a concern to you?  In
general terms it seems to have all the same intentions as 2.1 but with more
explicit terms where 2.1 was nonspecific.

As for that 8.6GB Windows download (from a slow server, I might also
mention) I am probably going to investigate WSL2 before attempting another
download.  Most all of the apps I have written in the last ~10 years have
ended up running on various flavors of Linux, not Windows.

**Comment by rochus-keller** [comment]
LGPL v2.1 allows for more flexibility. Remember that also the Linux project doesn't switch to GPL 3. One aspect that is relevant e.g. for embedded systems is the so called "Tivoization" (see https://en.wikipedia.org/wiki/Tivoization).

**Comment by MangoCats** [comment]
Ok makes sense, nothing I have ever been involved with trying to do, but I
get the desire.

One of my hobby frustrations with Qt has been their poor media player
implementations over the years.  The tech was there, in 2006 I implemented
a video snippet player using Qt for an educational tool, but every single
update would break it somehow.  Here in 2021 I made a simple mp3 player,
but again an update of the codecs broke it just a few months later.  There
is no good reason for software that old and simple to require such
maintenance, I'm glad I don't need to do it for a living.  The license
frustrations on top I'm sure are there to protect established players in
the industry.

**Comment by rochus-keller** [comment]
Please note that network support is ready.

**Comment by rochus-keller** [comment]
It's released, see https://github.com/rochus-keller/LeanQt/releases/tag/2022-10-21

**Comment by MangoCats** [comment]
Thanks!
