### ISSUE TITLE
TQt3?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/LeanQt#20]
Windows support is missing. The codebase is not even C++11 but it doesn't have the bloat of later Qt versions and is still being maintained and used by TDE.

https://mirror.git.trinitydesktop.org/gitea/TDE/tqt3/issues/52

**Comment by rochus-keller** [comment]
It nicely compiles and runs on Windows. Not sure what you mean.

**Comment by rochus-keller** [comment]
LeanQt doesn't have anything to do with TQ3; I don't understand why you post this as an issue here.
