### ISSUE TITLE
Bindings for LeanQt?

### ISSUE THREAD

**Issue by LexiconCode** [rochus-keller/LeanQt#7]
Depending on the scope would you consider bindings like PySide2 as a long-term goal?

**Comment by rochus-keller** [comment]
Personally I have no need for it. But the existing PySide code compatible with Qt 5.6 should actually also work with LeanQt; there is no GUI though.

**Comment by LexiconCode** [comment]
@rochus-keller That's encouraging.

I'll check back in when QtGui is implemented.

**Comment by rochus-keller** [comment]
> when QtGui is implemented

That's on my long term plan; I cannot promise today when that will be.

**Comment by rochus-keller** [comment]
I close this for now since existing bindings compatible with Qt 5.6.3 continue to be compatible as far as the required Qt feature is present in LeanQt.
