### ISSUE TITLE
so lean to the point it fails my production or user requirements

### ISSUE THREAD

**Issue by omac777** [rochus-keller/LeanQt#8]
Your language choice of Oberon I can respect that.   I found no gui bindings for Oberon. None.

Most users are accustomed to having phones with pens/stylus or laptops with pens/stylus'es. Most stylus devices and screens as a result do conform to wacom tablet and pen conventions.  

There are only truly 2 contenders out there for GUI toolkits that satisfy all requirements: GTK4 and QT.
Why is that?  They are the only existing apis for all hardware targets and operating systems that support all the usual accessibility requirements along with tablet/pen/stylus/touch/gesture.

I would recommend you reconsider your plan to not support tablet/pen/stylus/touch/gesture otherwise I think you will fail to find adopters in the younger crowds used to such habits with mobile devices and artistic inclinations.

As for my personal programming language preference, it is Rust.  For Surprisingly, you'll find a strong GTK4 gtk4-rs binding 
https://github.com/gtk-rs/gtk4-rs/tree/master/examples
already and the Ritual QT bindings 
https://rust-qt.github.io/qt/
https://github.com/rust-qt/examples
are thorough, straightforward and similar to yours as they do not try to keep up with more recent QT versions, but are thorough in support in earlier versions.
I won't go into the rationale as to why I prefer Rust over C/C++/Java/.NET/C#/Go, but the subtlety that there is a lot of momentum behind Rust should hint/nudge you to consider adopting it.

**Comment by rochus-keller** [comment]
> I would recommend you reconsider your plan to not support tablet/pen/stylus/touch/gesture otherwise

It's all in besides the QTabletEvent and its handling. You're the first and only one so far required it. If there is a true demand I can still integrate it. Though there is still original Qt, and I consider Qt on mobile devices to be of little use and not worth the effort.

> As for my personal programming language preference, it is Rust.

If thre is a Rust binding for Qt, chances are very good it also works with LeanQt. But I don't see it as my priority to provide bindings.

**Comment by omac777** [comment]
I'm not an Oberon user.  I don't foresee being a LeanQt user either.  That said I have spent a great deal of time researching bindings for go and rust with respect to gui bindings and I have shared my best perspectives with you with regards to gui bindings.

I have abandoned all languages as much as possible except for Rust.  I am surprised your binding made the news as I know nobody in my coding entourage whisper likings for Oberon and it has been over 30 years since I've seen an Oberon book anywhere.  All I can see you have a special perspective and it's difficult to appreciate it without a rationale provided.
   On Friday, November 11, 2022 at 09:28:43 a.m. EST, Rochus Keller ***@***.***> wrote:  
 
 



I would recommend you reconsider your plan to not support tablet/pen/stylus/touch/gesture otherwise


It's all in besides the QTabletEvent and its handling. You're the first and only one so far required it. If there is a true demand I can still integrate it. Though there is still original Qt, and I consider Qt on mobile devices to be of little use and not worth the effort.


As for my personal programming language preference, it is Rust.


If thre is a Rust binding for Qt, chances are very good it also works with LeanQt. But I don't see it as my priority to provide bindings.

**Comment by rochus-keller** [comment]
LeanQt doesn't have anything to do with my Oberon compiler and IDE implementations besides I'm using it as an implementation detail together with C++.

In favor of feasibility, I base my spare time projects on practical need, not hypothetical need. But it's actually the advantage of open source: anyone who has a need can do it themselves.
