### ISSUE TITLE
valgrind -v --leak-check=full --show-leak-kinds=all --track-origins=yes --tool=memcheck ./prog

### ISSUE THREAD

**Issue by sp00ck** [rochus-keller/LeanQt#9]
please check 

`valgrind -v --leak-check=full --show-leak-kinds=all --track-origins=yes --tool=memcheck ./program`

**Comment by rochus-keller** [comment]
Can you post a log please?

**Comment by sp00ck** [comment]
Where is problem
just install valgrind and run.
valgrind -v --leak-check=full --show-leak-kinds=all --track-origins=yes --tool=memcheck ./clock 


```
==33734== 
==33734== 2,976 (8 direct, 2,968 indirect) bytes in 1 blocks are definitely lost in loss record 36 of 36
==33734==    at 0x483AE7D: operator new(unsigned long) (vg_replace_malloc.c:342)
==33734==    by 0x428B21: RasterWindow::RasterWindow(QWindow*) (in /home/oooo/BUSY/output/clock)
==33734==    by 0x428960: AnalogClockWindow::AnalogClockWindow() (in /home/oooo/BUSY/output/clock)
==33734==    by 0x427DDA: main (in /home/oooo/BUSY/output/clock)
==33734== 
==33734== LEAK SUMMARY:
==33734==    definitely lost: 8 bytes in 1 blocks
==33734==    indirectly lost: 2,968 bytes in 26 blocks
==33734==      possibly lost: 304 bytes in 1 blocks
==33734==    still reachable: 752 bytes in 8 blocks
==33734==         suppressed: 0 bytes in 0 blocks
==33734== 
==33734== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)


```

**Comment by rochus-keller** [comment]
Ok, thanks; doesn't look like a big issue; apparently the window in the example is not deleted when closed; I will check.

**Comment by rochus-keller** [comment]
Meanwhile I implemented a Qmake generator for BUSY so I could use QtCreator and the built-in debugger and analyzer support to isolate the issue. It turned out that in the example RasterWindow class I inherited from original Qt the QBackingStore was not deleted; I added a destructor and now I don't see any leaks anymore.
